### ISSUE TITLE
После успешной оплаты статус заказа автоматически меняется с "Обработки" на "Выполнен"

### ISSUE THREAD

**Issue by hadjihanov** [PaycomUZ/woocommerce-payment-gateway#8]
Когда оформляется заказ, на начальном этапе Woocommerce присваивает заказу статус "В ожидании оплаты", а после оплаты переходит на статус "Обработка", а затем моментально переходит на статус "Выполнен", хотя наш заказ еще не был доставлен (еще не был выполнен), и по идее должен оставаться на статусе "Обработка" пока не будет доставлен клиенту и после этого вручную нами не переведен на статус "Выполнен". 

![Заметки к заказу](https://user-images.githubusercontent.com/31609827/79429689-4d54e580-7fe1-11ea-90cb-6d923febedf3.jpg)

Например, в 20:12 минут переходит на "Обработка", а затем сразу "Выполнен". 
Потом мне вручную приходится менять на "Обработка", так как он не будет отображаться на вкладке Обрабатываемых заказов, а также может ввести в заблуждение клиентов, что их заказ был "Выполнен".

Ознакомиться со статусами заказов Woocommerce можно на официальной странице https://docs.woocommerce.com/document/managing-orders/

![woocommerce-order-process-diagram](https://user-images.githubusercontent.com/31609827/79430087-d9ffa380-7fe1-11ea-88cc-d8a1520bbfb0.png)

**Comment by LipatovYuriy** [comment]
Добрый день. В чем суть вашего предложения на доработку?

**Comment by atxam** [comment]
Добрый день, о чем вообще речь? Я разве где то задал вопрос?

чт, 16 апр. 2020 г. в 13:42, Lipatov Yuriy <notifications@github.com>:

**Comment by LipatovYuriy** [comment]
А вы кто? Я задал вопрос пользователю hadjihanov.

**Comment by hadjihanov** [comment]
> 
> 
> Добрый день. В чем суть вашего предложения на доработку?

Добрый день!
Спасибо что откликнулись!
Нужно чтобы плагин Payme после успешной оплаты переводил статус с "Ожидание оплаты" на "Обработка". Но не переводил затем с "Обработка" на "Выполнен".
С "Обработка" на "Выполнен" переводит владелец магазина вручную, а не плагин. Также можно ознакомится со схемой на последнем изображении.

**Comment by LipatovYuriy** [comment]
Дело в том что есть площадки электронными товарами (и подобными) где важна полная автоматизация. Для них каждый раз вручную менять статуз заказа будет не очень удобно. Но в то же время есть площадки как в вашем примере - статус ВЫПОЛНЕН только после доставки и подтверждения целостности доставки клиентом.

Одним из решений является следующее:
В панели настроек плагина можно добавить два чекбокса (возможный текст):
 1. Автоматически переводить заказ в статус ВЫПОЛНЕН при успешной оплате
 2. Автоматически уменьшать количество товаров на складе в случае успешной оплаты.
Соответственно при установки чекбокса №1 в активное состояние, чекбокс №2 так же автоматически становится активным, потому как необходимо уменьшать остаток на складе при автоматическом завершении заказа. Но в Вашем случае необходимо активировать только чекбокс №2.
Подтвердите правильность понимания Вашей задачи в соответствии с Вашей бизнес логикой.

**Comment by hadjihanov** [comment]
Всё верно. Было-бы хорошо иметь чекбокс в настройках плагина, как вы и написали.
То есть, всё остается, как сейчас на первом изображении:
1. Уровни запасов уменьшаются
2. Статус с "В ожидании оплаты" меняется на "Обработка", но не переходит автоматически на "Выполнен"

Спасибо большое!

**Comment by hadjihanov** [comment]
Я так думаю, что достаточно сделать 1 чекбокс на "При успешной оплате автоматически переводить статус заказа в ВЫПОЛНЕН"

**Comment by LipatovYuriy** [comment]
Добрый день. Запрошенная Вами функция реализована
![Firefox_Screenshot_2020-04-17T12-20-45 024Z](https://user-images.githubusercontent.com/28455436/79569183-d8a4a880-80bf-11ea-9e79-c84acdb4cc4f.png)

В настройках добавил чекбокс для управления.

**Comment by hadjihanov** [comment]
Добрый день!
Премного благодарен!
Если я правильно понял, новая версия появится на этой странице https://github.com/PaycomUZ/woocommerce-payment-gateway/releases ?

**Comment by LipatovYuriy** [comment]
Не совсем. Так как я не вхожу в группу contributors то нужно подождать когда коллеги подтвердят pull request и сделают merge. Для справки: новый релиз 1.4.8

**Comment by hadjihanov** [comment]
Большое спасибо!
